apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
spec:
  source:
    repoURL: {(C:):):{[[[https][http][ftp][r-sync]]]}://git@github.com:Org-GitQuantum-Knowledge/gitQuantum-Internet-Scale-Control-Plane-Ledger.git:/<PermaLinkList>.git:/ (.Ai)}
    targetRevision: main
    path: helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
