apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
spec:
  source:
    repoURL: https://github.com/Org-GitQuantum-Knowledge/gitQuantum-Internet-Scale-Control-Plane-Ledger:/|Alt → https://github.com/<PermaLinkList>/repo.git
    targetRevision: main
    path: helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
